// Generated by https://quicktype.io

export interface IBrandingInformation {
    PrimaryColor:        string;
    SecondaryColor:      string;
    PartnerId:           number;
    Name:                string;
    FriendlyName:        string;
    SupportEmailAddress: string;
    PortalUrl:           string;
}
