// Generated by https://quicktype.io

export interface IBrandingInformation {
    primaryColor:        string;
    secondaryColor:      string;
    partnerId:           number;
    name:                string;
    friendlyName:        string;
    supportEmailAddress: string;
    portalUrl:           string;
}
