// Generated by https://quicktype.io

export interface ISnapshotResponse {
  snapshotId:               number;
  snapshotDate:             string;
  processedDrivePartitions: ProcessedDrivePartition[];
  nonProcessedDrives:       any[];
  notAvailableYetDrives:    any[];
  isComplete:               boolean;
}

export interface ProcessedDrivePartition {
  driveId: number;
  length:  number;
  letter:  string;
  label:   string;
  offset:  number;
}
