// Generated by https://quicktype.io

export interface IUserComputerResponse {
  name:                           string;
  computerId:                     number;
  machineName:                    string;
  alias:                          null | string;
  subscriptionExpirationDate:     string;
  subscriptionIsExpired:          boolean;
  subscriptionWillExpireThisWeek: boolean;
  hasAutomaticSubscription:       boolean;
}
