export interface IUserResponse {
  UserId: number;
  Profiles: number;
  Email: string;
  Culture: string;
  Name: string;
  LastName: string;
  IsResqtimeUser: boolean;
  PartnerSupportEmail: string;
  PartnerId: number
}
// Generated by https://quicktype.io

export interface IAuthenticatedUserResponse {
  Profile:             number;
  Email:               string;
  Culture:             string;
  Name:                string;
  LastName:            string;
  IsLoozendUser:       boolean;
  PartnerSupportEmail: string;
}
