export interface IUserResponse {
  UserId: number;
  Profiles: number;
  Email: string;
  Culture: string;
  Name: string;
  LastName: string;
  IsResqtimeUser: boolean;
  PartnerSupportEmail: string;
  PartnerId: number
}
// Generated by https://quicktype.io

export interface IAuthenticatedUserResponse {
  profile:             number;
  email:               string;
  culture:             string;
  name:                string;
  lastName:            string;
  isLoozendUser:       boolean;
  partnerSupportEmail: string;
}
