/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PartitionDto } from './partitionDto';


export interface DriveDto { 
    driveId?: number;
    driveSnapshotId?: number;
    model?: string | null;
    lengthInGigas?: number;
    bytesPerSector?: number;
    isRemovable?: boolean;
    initializeUploadDate?: string | null;
    finalizeUploadDate?: string | null;
    partitions?: Array<PartitionDto> | null;
}

