/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComputerStatusDto } from './computerStatusDto';


export interface GetComputersFilter { 
    freeText?: string | null;
    minSubscriptionExpirationDate?: string | null;
    maxSubscriptionExpirationDate?: string | null;
    expireOnNextNDays?: number | null;
    from?: string | null;
    to?: string | null;
    showExpired?: boolean;
    status?: Array<ComputerStatusDto> | null;
    showDeleted?: boolean;
    showNotExpired?: boolean;
}

