/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilteredComputer } from './filteredComputer';


export interface GetPartnerComputersResponse { 
    totalItemCount?: number;
    page?: number;
    pageCount?: number;
    items?: Array<FilteredComputer> | null;
    extendedDetails?: any | null;
    pageItemCount?: number;
    dangerComputerCount?: number;
    reviewComputerCount?: number;
    syncingComputerCount?: number;
    correctComputerCount?: number;
}

