/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetUsersFilters {
    freeText?: string | null;
    showDeleted?: boolean | null;
    hasDrivesUploading?: boolean | null;
    hasProcessedComputers?: boolean | null;
    hasDrivesProcessingUpload?: boolean | null;
    hasDrivesBrowsable?: boolean | null;
    connectionStatus?: ConnectionStatus | null; //connectionStatus
}
export enum ConnectionStatus {
  ALL = 'ALL',
  Online = 'Online',
  Offline = 'Offline'
}
