/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComputerCreatedEvent { 
    computerId?: number;
    userId?: number;
    licenseId?: string | null;
    licenseCreatedDate?: string;
    licenseExpirationDate?: string;
    downloadCount?: number;
}

