/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ComputerDetailedStatusDto = 'Correct' | 'Expired' | 'TdcOver80Percentage' | 'TdcDelayed12Hours' | 'TdcNotCreated' | 'RebootPending' | 'Disconnected5Days' | 'ConsoleUninstalled' | 'ConsoleNotUpdated' | 'ConsoleFailure' | 'DisconnectedInInitialUpload' | 'TdcOver20Percentage' | 'TdcDelayed6Hours' | 'Disconnected3Days' | 'UploadingPaused' | 'ReSyncing' | 'InitialUpload';

export const ComputerDetailedStatusDto = {
    Correct: 'Correct' as ComputerDetailedStatusDto,
    Expired: 'Expired' as ComputerDetailedStatusDto,
    TdcOver80Percentage: 'TdcOver80Percentage' as ComputerDetailedStatusDto,
    TdcDelayed12Hours: 'TdcDelayed12Hours' as ComputerDetailedStatusDto,
    TdcNotCreated: 'TdcNotCreated' as ComputerDetailedStatusDto,
    RebootPending: 'RebootPending' as ComputerDetailedStatusDto,
    Disconnected5Days: 'Disconnected5Days' as ComputerDetailedStatusDto,
    ConsoleUninstalled: 'ConsoleUninstalled' as ComputerDetailedStatusDto,
    ConsoleNotUpdated: 'ConsoleNotUpdated' as ComputerDetailedStatusDto,
    ConsoleFailure: 'ConsoleFailure' as ComputerDetailedStatusDto,
    DisconnectedInInitialUpload: 'DisconnectedInInitialUpload' as ComputerDetailedStatusDto,
    TdcOver20Percentage: 'TdcOver20Percentage' as ComputerDetailedStatusDto,
    TdcDelayed6Hours: 'TdcDelayed6Hours' as ComputerDetailedStatusDto,
    Disconnected3Days: 'Disconnected3Days' as ComputerDetailedStatusDto,
    UploadingPaused: 'UploadingPaused' as ComputerDetailedStatusDto,
    ReSyncing: 'ReSyncing' as ComputerDetailedStatusDto,
    InitialUpload: 'InitialUpload' as ComputerDetailedStatusDto
};

