/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FilteredUsers { 
    userId?: number;
    name?: string | null;
    email?: string | null;
    culture?: string | null;
    createdDate?: string;
    cancelledDate?: string | null;
    sourceIp?: string | null;
    computersCount?: number;
    processedComputersCount?: number;
    uploadingComputersCount?: number;
    driveProcessedCount?: number;
    driveUploadingCount?: number;
    readonly hasDrivesUploading?: boolean;
    readonly hasProcessedComputers?: boolean;
    partnerName?: string | null;
    partnerId?: number | null;
    isOnline?: boolean;
    lastOnlineDate?: string | null;
    isDeleted?: boolean;
    isIntegrator?: boolean;
}

