/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetAuthenticatedUserResponse { 
    UserId?: number;
    Profiles?: number;
    Email?: string | null;
    Culture?: string | null;
    Name?: string | null;
    LastName?: string | null;
    IsResqtimeUser?: boolean;
    PartnerSupportEmail?: string | null;
    PartnerId?: number;
}

