/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetItemsRequestOrder } from './getItemsRequestOrder';
import { GetItemsRequestPaging } from './getItemsRequestPaging';
import { GetUsersFilters } from './getUsersFilters';


export interface GetUsersRequest { 
    filter?: GetUsersFilters;
    order?: GetItemsRequestOrder;
    paging?: GetItemsRequestPaging;
}

