/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetUserDetailsResponse { 
    mustChangePassword?: boolean;
    createdDate?: string;
    cancelledDate?: string | null;
    userId?: number;
    clientId?: number;
    name?: string | null;
    lastName?: string | null;
    email?: string | null;
    culture?: string | null;
    partnerId?: number;
    partnerName?: string | null;
}

