/**
 * AdminApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DriveDto } from './driveDto';
import { HardwareInfoDto } from './hardwareInfoDto';


export interface GetUserComputersResponse { 
    computerId?: number;
    creationDate?: string;
    cancelledDate?: string | null;
    lastSnapshotDate?: string;
    drives?: Array<DriveDto> | null;
    hardwareInfo?: HardwareInfoDto;
    alias?: string | null;
    subscriptionExpirationDate?: string | null;
}

